In [1]:
import pandas as pd

salary = pd.Series(
    [25000, 32000, 28000, 45000, 38000,
     50000, 30000, 42000, 35000, 60000],
    index=[
        "Zahid", "Suhana", "Arosh", "Furkhan", "Chandini",
        "Asfiya", "Tayab", "Faizal", "Sufiyan", "Mirzan"
    ],
    name="Salary"
)

print(salary)

Zahid       25000
Suhana      32000
Arosh       28000
Furkhan     45000
Chandini    38000
Asfiya      50000
Tayab       30000
Faizal      42000
Sufiyan     35000
Mirzan      60000
Name: Salary, dtype: int64

In [3]:
#Reset the index of the salary Series and convert it into a DataFrame.Hint: Use reset_index() with to_frame().
salary.reset_index()

      index  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000
6     Tayab   30000
7    Faizal   42000
8   Sufiyan   35000
9    Mirzan   60000

In [4]:
#Reset the index and store the result in a new variable called df.Hint: Assign the result to df.
df=salary.reset_index()
df

      index  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000
6     Tayab   30000
7    Faizal   42000
8   Sufiyan   35000
9    Mirzan   60000

In [7]:
#Reset the index and keep the original Series unchanged.Hint: reset_index() returns a new object by default.
new_salary=salary.reset_index()
new_salary

      index  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000
6     Tayab   30000
7    Faizal   42000
8   Sufiyan   35000
9    Mirzan   60000

In [10]:
#Reset the index and rename the columns to Employee and Salary.Hint: Convert to a DataFrame, then rename the columns.
salary.reset_index().rename(columns={"index":"Employee","Salary":"Salary"})

   Employee  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000
6     Tayab   30000
7    Faizal   42000
8   Sufiyan   35000
9    Mirzan   60000

In [11]:
#Reset the index and make Employee the default numerical index.Hint: The default index starts at 0.
salary.reset_index(drop=True)

0    25000
1    32000
2    28000
3    45000
4    38000
5    50000
6    30000
7    42000
8    35000
9    60000
Name: Salary, dtype: int64

In [14]:
#Reset the index, then display only the first five rows.Hint: Use head(5).
new_salary=salary.reset_index()
print(new_salary)
print(new_salary[0:6])

      index  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000
6     Tayab   30000
7    Faizal   42000
8   Sufiyan   35000
9    Mirzan   60000
      index  Salary
0     Zahid   25000
1    Suhana   32000
2     Arosh   28000
3   Furkhan   45000
4  Chandini   38000
5    Asfiya   50000